### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by ghost** [shu-paulsideleau/shu-bowling#6]
# As a bowler, I want to conduct my round payment at my lane, without having to check out with an employee.

A bowler would pay for the their purchase prior to starting on an open.  If they already had an account they would log in or create one.  They would fill out the payment options.

Option on this page would include:

- Cash or Credit

- Credit Card #, Exp, CCV

- Name(First, Last)

- Address Info

- number of rounds

At the end of the round if the user wants to play another round they have the ability to do so once the previous number of rounds has been conducted.  If they paid with a card it would just add to the charge, if with cash they would just put more in the machine.

**Comment by robantonucci** [comment]
# **SHOULD THIS BE MERGED WITH #5 ?**

**Comment by togadiyaj** [comment]
Based on discussion we concluded that we will not do payment on website, so closing this user story.
